language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install: "pip install -r requirements.txt --use-mirrors"
script: "./run_tests.py"
before_script:
  - wget https://github.com/vespian/pymisc/archive/1.2.0.tar.gz -O /tmp/pymisc-1.2.0.tar.gz
  - tar -xvf /tmp/pymisc-1.2.0.tar.gz -C /tmp/
  - cd /tmp/pymisc-1.2.0/ && /tmp/pymisc-1.2.0/setup.py install
  - cd $TRAVIS_BUILD_DIR
